CapstoneProject/Controllers/AppointmentController.cs
using CapstoneProject.Data;
using CapstoneProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CapstoneProject.Controllers
{
    public class AppointmentController : Controller
    {
        private ApplicationDbContext _context;
        public AppointmentController(ApplicationDbContext context)
        {
            _context = context;
        }

        public ActionResult Index(double addDays)
        {
            double currentDay = DateTime.Today.DayOfYear;
            if (addDays != 0)
            { 
                currentDay = addDays;
            }

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var salesperson = _context.Salespeople
                .Include(s => s.Projects)
                   .ThenInclude(p => p.Customer)
                .Include(s => s.Projects)
                    .ThenInclude(p => p.Grass)
                .Include(s => s.Appointments)
                .Where(s => s.IdentityUserId == userId)
                .FirstOrDefault();
            Day day = new Day();
            ViewBag.SelectedWeek = day.SelectWeek(currentDay);

            return View(salesperson);
        }

        public ActionResult AddAppointments(int id)
        {
            int dayOfYear = id;
            int year = DateTime.Now.Year;
            DateTime date = new DateTime(year, 1, 1).AddDays(dayOfYear - 1);
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var salesperson = _context.Salespeople.Include(s=>s.Appointments).Where(s => s.IdentityUserId == userId).FirstOrDefault();
            var appointments = _context.Appointments;
            for (int i = 0; i < 4; i++)
            {
                int start = 8 + (i * 2);
                int end = 10 + (i * 2);
                Appointment appt = new Appointment()
                {
                    AppointmentStart = date.AddHours(start),
                    AppointmentEnd = date.AddHours(end),
                    Notes = "This appointment is open",
                    InteractionType = "Nothing to show",
                    IsOpen = true,
                    IsBooked = false,
                    IsCompleted = false
                };
                bool value = _context.Appointments.Where(a => a.AppointmentStart == appt.AppointmentStart).Any();
                if (value == true)
                {
                    continue;
                }
                else
                {
                    appointments.Add(appt);
                    _context.SaveChanges();
                    salesperson.Appointments.Add(appt);
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("Index", "Salesperson");
        }

        [HttpGet]
        public ActionResult BookOpenAppointment(int id)
        {
            Appointment appt = _context.Appointments.Where(a => a.id == id).FirstOrDefault();
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            Salesperson salesperson = _context.Salespeople.Where(s => s.IdentityUserId == userId).FirstOrDefault();
            ViewBag.Projects = _context.Projects.Where(p => p.Salesperson.id == salesperson.id && p.IsSold == false).ToList();
            return View(appt);
        }

        [HttpPost]
        public ActionResult BookOpenAppointment(Appointment appt)
        {
            Appointment apptInDB = _context.Appointments.Where(a => a.id == appt.id).FirstOrDefault();
            apptInDB.IsBooked = true;
            apptInDB.IsCompleted = false;
            apptInDB.IsOpen = false;
            apptInDB.ProjID = appt.ProjID;
            apptInDB.InteractionType = appt.InteractionType;
            apptInDB.Notes = appt.Notes;
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Details(int id)
        {
            var appointment = _context.Appointments
                .Where(a => a.id == id)
                .Include(a=>a.Project)
                    .ThenInclude(p =>p.Customer)
                .Include(a => a.Project)
                    .ThenInclude(p => p.Salesperson)
                .Include(a => a.Project)
                    .ThenInclude(p => p.Grass)
                .FirstOrDefault();
            ViewBag.MapUrl = $"https://www.google.com/maps/embed/v1/place?key=" + Utilities.APIs.MapsKey + "&q=" + appointment.Project.LatAddress.ToString() + "," + appointment.Project.LongAddress.ToString();
            return View(appointment);
        }
        public ActionResult Edit(int id)
        {
            var appointment = _context.Appointments.Where(a => a.id == id).FirstOrDefault();
            return View(appointment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Appointment appointment)
        {
            var appointmentInDB = _context.Appointments
                .Include(a=>a.Project)
                .Where(a => a.id == appointment.id).FirstOrDefault();
            appointmentInDB.Notes = appointment.Notes;
            appointmentInDB.InteractionType = appointment.InteractionType;
            _context.SaveChanges();
            return RedirectToAction("Index", "Salesperson");
        }

        public ActionResult Delete(int id)
        {

            var appointment = _context.Appointments
                .Include(a => a.Project)
                .ThenInclude(p => p.Salesperson)
                .Where(a => a.id == id)
                .FirstOrDefault();
            var salesperson = _context.Salespeople.Where(s=>s.id == appointment.Project.SalesID).FirstOrDefault();
            appointment.IsBooked = false;
            appointment.IsCompleted = false;
            appointment.IsOpen = true;
            appointment.ProjID = null;
            appointment.Notes = "This appointment is open";
            appointment.Project = null;
            _context.SaveChanges();
            salesperson.Appointments.Add(appointment);
            _context.SaveChanges();
            return RedirectToAction("Index","Home");
        }
        public ActionResult Complete(Appointment appointment)
        {
            var appointmentInDB = _context.Appointments
                .Include(a => a.Project)
                    .ThenInclude(p=>p.Salesperson)
                .Include(a => a.Project)
                    .ThenInclude(p => p.Customer)
                .Include(a => a.Project)
                    .ThenInclude(p => p.Grass)
                .Where(a => a.id == appointment.id).FirstOrDefault();
            appointmentInDB.IsCompleted = true;
            appointmentInDB.IsBooked = true;
            appointmentInDB.IsOpen = false;
            if(appointment.Notes == null)
            {
                appointmentInDB.Notes = "No notes from the appointment";
            }
            else
            {
                appointmentInDB.Notes = appointment.Notes;
            }
            if(appointment.InteractionType == null) 
            {
                appointmentInDB.InteractionType = "No interaction type noted";
            }
            else
            {
                appointmentInDB.InteractionType = appointment.InteractionType;

            }
            int id = appointmentInDB.Project.id;
            _context.SaveChanges();
            return RedirectToAction("Index", "Salesperson");
        }
    }
}

CapstoneProject/Controllers/ProjectController.cs
using CapstoneProject.Data;
using CapstoneProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CapstoneProject.Controllers
{
    public class ProjectController : Controller
    {
        private ApplicationDbContext _context;

        public ProjectController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: ProjectController
        public ActionResult Index()
        {
            return View();
        }

        // GET: ProjectController/Details/5
        public ActionResult Details(int id)
        {
            var project = _context.Projects.Where(p => p.id == id)
                    .Include(p => p.Salesperson)
                    .ThenInclude(s=>s.Appointments)
                    .Include(p => p.Customer)
                    .Include(p => p.Grass)
                    .Include(p=>p.Appointments)
                    .FirstOrDefault();
            _context.Projects.Update(project);
            _context.SaveChanges();
            ViewBag.MapUrl = $"https://www.google.com/maps/embed/v1/place?key=" + Utilities.APIs.MapsKey + "&q=" + project.LatAddress.ToString() + "," + project.LongAddress.ToString();

            //Adding an appointment for testing;
            return View(project);
        }

        public ActionResult ConfirmAppointment(int apptId, int id)
        {
            Project project = _context.Projects.Where(p => p.id == id).FirstOrDefault();
            project.Salesperson = _context.Salespeople.Where(s => s.id == project.SalesID).FirstOrDefault();
            project.Customer = _context.Customers.Where(c => c.id == project.CustID).FirstOrDefault();
            Appointment appt = _context.Appointments.Where(a => a.id == apptId).FirstOrDefault();
            appt.IsBooked = true;
            appt.IsOpen = false;
            appt.ProjID = project.id;
            appt.id = apptId;
            project.Salesperson.Appointments.Add(appt);
            _context.SaveChanges();
            string body = $"Your appointment with {project.Salesperson.FirstName} on {appt.AppointmentStart.DayOfWeek} , {appt.AppointmentStart.ToString("MMMM dd")} at {project.Appointments.Last().AppointmentStart.ToString("t")} has been confirmed.  If you need to change your appointmnet, please login to our website.";
            project.SendText(body);
            return RedirectToAction("Index", "Home");
        }
        public ActionResult ConvertToSale(int id)
        {
            Project project = _context.Projects.Include(a=>a.Appointments).Include(p => p.Salesperson).Where(p => p.id == id).FirstOrDefault();
            var salesperson = _context.Salespeople.Where(s => s.id == project.SalesID).Include(s=>s.Appointments).FirstOrDefault();
            project.IsSold = true;
            var OpenAppointments = project.Appointments.Where(a => a.IsBooked == true && a.IsCompleted == false).ToList();
            foreach(Appointment appt in OpenAppointments)
            {
                appt.IsOpen = true;
                appt.IsBooked = false;
                appt.IsCompleted = false;
                appt.ProjID = null;
                appt.Project = null;
                appt.InteractionType = "Open appointment";
                appt.Notes = "This appointment is open";
                _context.SaveChanges();
                salesperson.Appointments.Add(appt);
                _context.SaveChanges();
            }
            project.Salesperson.TotalProjects += 1;
            project.Salesperson.TotalSales += project.Cost;
            project.ConvertedToSale = DateTime.Now;
            _context.SaveChanges();
            return RedirectToAction("Index", "Salesperson");

        }
        [HttpGet]
        public ActionResult SalespersonCreate() 
        {
            ViewBag.Customers = _context.Customers.ToList();
            return View();
        }

        [HttpPost]
        // GET: ProjectController/Create
        public ActionResult SalespersonCreate(Project project)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var salesperson = _context.Salespeople.Where(s => s.IdentityUserId == userId).FirstOrDefault();
            project.Salesperson = salesperson;
            project.SalesID = salesperson.id;
            project.IsSold = false;
            project.Grass = _context.Grasses.Where(g => g.id == project.GrassID).FirstOrDefault();
            project.Name = project.StreetAddress + ": " + project.SquareFootage.ToString() + " sq/ft of " + project.Grass.Name;
            if (project.IsProjectAreaCleared == false)
            {
                project.Cost = project.SquareFootage * (project.Grass.Cost + 1);
                project.Description = $"This is a {project.Grass.Name} project of {project.SquareFootage} quare feet, located at {project.StreetAddress}, {project.CityAddress}, {project.StreetAddress} {project.ZipAddress}  The area needs to be cleared."
                    + $"  The total project cost is expected to be ${project.Cost}.00.";
            }
            else
            {
                project.Cost = project.SquareFootage * project.Grass.Cost;
                project.Description = $"This is a {project.Grass.Name} project of {project.SquareFootage}, located at {project.StreetAddress}, {project.CityAddress}, {project.StreetAddress} {project.ZipAddress}.  The area is ready for grass."
                    + $"  The total project cost is expected to be {project.Cost}.";
            }
            string address = project.StreetAddress
                 + ", "
                 + project.CityAddress
                 + ", "
                 + project.StateAddress
                 + " "
                 + project.ZipAddress;
            project.SetGeocode(address);
            project.Salesperson.TotalPossibleSales += project.Cost;
            project.Salesperson.TotalOpportunities += 1;
            _context.Projects.Add(project);
            _context.SaveChanges();
            return RedirectToAction("Details", project);
        }

        // POST: ProjectController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Project project)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = _context.Customers.Where(c => c.IdentityUserId == userId).FirstOrDefault();
            if(customer == null)
            {
                return RedirectToAction("Create", "Customer");
            }
            project.Customer = customer;
            project.CustID = customer.id;
            project.Appointments = new List<Appointment>();
            project.IsSold = false;
            project.StreetAddress = customer.StreetAddress;
            project.CityAddress = customer.CityAddress;
            project.StateAddress = customer.StateAddress;
            project.ZipAddress = customer.ZipAddress;
            project.Grass = _context.Grasses.Where(g => g.id == project.GrassID).FirstOrDefault();
            project.Name = project.StreetAddress + ": " + project.SquareFootage.ToString() + " sq/ft of " + project.Grass.Name;
            if (project.IsProjectAreaCleared == false)
            {
                project.Cost = project.SquareFootage * (project.Grass.Cost + 1);
                project.Description = $"This is a {project.Grass.Name} project of {project.SquareFootage} quare feet, located at {project.StreetAddress}, {project.CityAddress}, {project.StreetAddress} {project.ZipAddress}  The area needs to be cleared."
                    + $"  The total project cost is expected to be ${project.Cost}.00.";
            }
            else
            {
                project.Cost = project.SquareFootage * project.Grass.Cost;
                project.Description = $"This is a {project.Grass.Name} project of {project.SquareFootage}, located at {project.StreetAddress}, {project.CityAddress}, {project.StreetAddress} {project.ZipAddress}.  The area is ready for grass."
                    + $"  The total project cost is expected to be {project.Cost}.";
            }
            string address = project.StreetAddress
                 + ", "
                 + project.CityAddress
                 + ", "
                 + project.StateAddress
                 + " "
                 + project.ZipAddress;
            project.SetGeocode(address);
            var salesperson = _context.Salespeople.Where(s => s.ZipAddress == project.ZipAddress).FirstOrDefault();
            if (salesperson == null)
            {
                List<Salesperson> salespeople = _context.Salespeople.Include("Appointments").ToList();
                project.SalesID = salespeople[0].id;
                project.Salesperson = salespeople[0];
            }
            else
            {
                project.SalesID = salesperson.id;
                project.Salesperson = salesperson;
            }
            project.Salesperson.TotalPossibleSales += project.Cost;
            project.Salesperson.TotalOpportunities += 1;
            _context.Projects.Add(project);
            _context.SaveChanges();
            return RedirectToAction("Details", project);
        }

        // GET: ProjectController/Edit/5
        public ActionResult Edit(int id)
        {
            var project = _context.Projects.Where(p => p.id == id).FirstOrDefault();
            return View(project);
        }

        // POST: ProjectController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Project project)
        {
            var projectInDB = _context.Projects
                .Where(p => p.id == project.id)
                .Include(p=>p.Grass)
                .FirstOrDefault();

CapstoneProject/Views/Salesperson/CreateAppointments.cshtml
@model CapstoneProject.Models.Salesperson

@{
    ViewData["Title"] = "CreateAppointments";
}
<h4>Select A Day</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <div class="data-row">
            <p>
                Your currently have @Model.Appointments.Count().ToString() appointment slots available through @ViewBag.LastAppointment.ToString("dddd, MMMM d, yyyy")
            </p>
        </div>
        <form asp-action="CreateAppointments" asp-route-id="@Model">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NewAppointment" class="control-label"></label>
                <input asp-for="NewAppointment" asp-format="{MM/dd/yyyy}" class="form-control" />
                <span asp-validation-for="NewAppointment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="id" value="@Model.id"class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CapstoneProject/Views/Salesperson/Index.cshtml
@model CapstoneProject.Models.Salesperson
<div class="page-section">
    <div class="heading-container">
        <h1>Sales Dashboard</h1>
        <ul>
            <li><a asp-action="Edit" asp-route-id="@Model.id">Edit Profile</a></li>
        </ul>
    </div>
</div>
<div class="row" style="min-height: 672px;">
    <div class="col-9 page-section">
        @* This is our day column *@
        <div class="calendar-container">
            <div class="row calendar-header">
                <a class="col-2" asp-action="Index" asp-controller="Salesperson" asp-route-addDays="@ViewBag.SelectedWeek[0].Date.AddDays(-7).DayOfYear">
                    <i class="fas fa-arrow-alt-circle-left fa-2x"></i>
                </a>
                <h2 class="col-8">Calendar for: @ViewBag.SelectedWeek[1].Date.ToString("MM/dd/yyyy") - @ViewBag.SelectedWeek[5].Date.ToString("MM/dd/yyyy")</h2>
                <a class="col-2" asp-action="Index" asp-controller="Salesperson" asp-route-addDays="@ViewBag.SelectedWeek[0].Date.AddDays(7).DayOfYear">
                    <i class="fas fa-arrow-alt-circle-right fa-2x"></i>
                </a>
            </div>
            <div id="calendar" class="row calendar-body">
                @for (int i = 1; i <= 5; i++)
                {
                    //If current day
                    @if (@ViewBag.SelectedWeek[i].Date == DateTime.Today)
                    {
                <div class="calendar-today">
                    <div class="calendar-day-header">
                        <h3>
                            @ViewBag.SelectedWeek[i].Date.DayOfWeek<br /> @ViewBag.SelectedWeek[i].Date.ToString("MM/dd/yyyy")
                        </h3>
                    </div>
                    @if (Model.Appointments.Where(a => a.AppointmentStart.Date == ViewBag.SelectedWeek[i].Date).Count() == 0)
                    {
                        @if (ViewBag.SelectedWeek[i].Date > DateTime.Now.Date)
                        {
                            <a asp-action="AddAppointments" asp-controller="Appointment" asp-route-id="@ViewBag.SelectedWeek[i].Date.DayOfYear">
                                <div class="appointment-add booked">
                                    <h4>Add appointments</h4>
                                </div>
                            </a>
                        }
                    }
                    else
                    {
                        <div>
                            @foreach (Appointment appt in Model.Appointments.Where(a => a.AppointmentStart.Date == ViewBag.SelectedWeek[i].Date).OrderBy(a => a.AppointmentStart).ToList())
                            {
                                @if (appt.IsBooked == true && appt.IsCompleted == false && appt.AppointmentEnd.Date >= DateTime.Now.Date)
                                {
                                    <a asp-action="Details" asp-controller="Appointment" asp-route-id="@appt.id">
                                        <div class="appointment booked">
                                            <h4>@appt.AppointmentStart.ToString("h:mm") - @appt.AppointmentEnd.ToString("h:mm")</h4>
                                            <h4>BOOKED</h4>
                                            <p>@appt.Project.StreetAddress</p>
                                        </div>
                                    </a>
                                }
                                @if (appt.IsBooked == false && appt.IsCompleted == false)
                                {
                                    <a asp-action="BookOpenAppointment" asp-controller="Appointment" asp-route-id="@appt.id">
                                        <div class="appointment unbooked">
                                            <h4>@appt.AppointmentStart.ToString("h:mm") - @appt.AppointmentEnd.ToString("h:mm")</h4>
                                            <h4>OPEN</h4>
                                        </div>
                                    </a>
                                }
                                @if (appt.IsCompleted == true)
                                {
                                    <a asp-action="Details" asp-controller="Appointment" asp-route-id="@appt.id">
                                        <div class="appointment completed">
                                            <h4>@appt.AppointmentStart.ToString("h:mm") - @appt.AppointmentEnd.ToString("h:mm")</h4>
                                            <h4>COMPLETED</h4>
                                            <p>@appt.Project.StreetAddress</p>
                                        </div>
                                    </a>
                                }
                                @if (appt.IsCompleted == false && appt.IsBooked == true && appt.AppointmentEnd.Date < DateTime.Now.Date)
                                {
                                    <a asp-action="Details" asp-controller="Appointment" asp-route-id="@appt.id">
                                        <div class="appointment overdue">
                                            <h4>@appt.AppointmentStart.ToString("h:mm") - @appt.AppointmentEnd.ToString("h:mm")</h4>
                                            <h4>COMPLETED</h4>
                                            <p>@appt.Project.StreetAddress</p>
                                        </div>
                                    </a>
                                }
                            }
                        </div>
                    }
                </div>
                    }
                    else
                    {
            <div class="calendar-nottoday">
                <div class="calendar-day-header">
                    <h3>
                        @ViewBag.SelectedWeek[i].Date.DayOfWeek<br /> @ViewBag.SelectedWeek[i].Date.ToString("MM/dd/yyyy")
                    </h3>
                </div>
                @if (Model.Appointments.Where(a => a.AppointmentStart.Date == ViewBag.SelectedWeek[i].Date).Count() == 0)
                {
                    @if (ViewBag.SelectedWeek[i].Date > DateTime.Now.Date)
                    {
                        <a asp-action="AddAppointments" asp-controller="Appointment" asp-route-id="@ViewBag.SelectedWeek[i].Date.DayOfYear" >
                            <div class="appointment-add booked">
                                <h4>Add appointments</h4>
                            </div> 
                        </a>
                    }
                 }
                    else
                    {
                    <div>
                        @foreach (Appointment appt in Model.Appointments.Where(a => a.AppointmentStart.Date == ViewBag.SelectedWeek[i].Date).OrderBy(a => a.AppointmentStart).ToList())
                        {
                            @if (appt.IsBooked == true && appt.IsCompleted == false && appt.AppointmentEnd > DateTime.Now.Date)
                            {
                                <a asp-action="Details" asp-controller="Appointment" asp-route-id="@appt.id">
                                    <div class="appointment booked">
                                        <h4>@appt.AppointmentStart.ToString("h:mm") - @appt.AppointmentEnd.ToString("h:mm")</h4>
                                        <h4>BOOKED</h4>
                                        <p>@appt.Project.StreetAddress</p>
                                    </div>
                                </a>
                            }
                            @if (appt.IsBooked == false && appt.IsCompleted == false && appt.AppointmentEnd.Date > DateTime.Now.Date)
                            {
                                <a asp-action="BookOpenAppointment" asp-controller="Appointment" asp-route-id="@appt.id">
                                    <div class="appointment unbooked">
                                        <h4>@appt.AppointmentStart.ToString("h:mm") - @appt.AppointmentEnd.ToString("h:mm")</h4>
                                        <h4>OPEN</h4>
                                    </div>
                                </a>
                            }
                            @if (appt.IsCompleted == true)
                            {
                                <a asp-action="Details" asp-controller="Appointment" asp-route-id="@appt.id">
                                    <div class="appointment completed">
                                        <h4>@appt.AppointmentStart.ToString("h:mm") - @appt.AppointmentEnd.ToString("h:mm")</h4>
                                        <h4>COMPLETED</h4>
                                        <p>@appt.Project.StreetAddress</p>
                                    </div>
                                </a>
                            }
                            @if (appt.IsCompleted == false && appt.IsBooked == true && appt.AppointmentEnd.Date < DateTime.Now.Date)
                            {
                                <a asp-action="Details" asp-controller="Appointment" asp-route-id="@appt.id">
                                    <div class="appointment overdue">
                                        <h4>@appt.AppointmentStart.ToString("h:mm") - @appt.AppointmentEnd.ToString("h:mm")</h4>
                                        <h4>OVERDUE</h4>
                                        <p>@appt.Project.StreetAddress</p>
                                    </div>
                                </a>
                            }
                        }
                    </div>
                }
            </div>
                    }
                }
            </div>
        </div>
    </div>
    <div class="col-3 page-section">
        <div class="calendar-header">
            <h2>My Statistics</h2>
        </div>
        <div>
            @*<div style="width: 100%; min-height: 10rem;">
                <canvas style="min-height: 10rem; width: 100%;" id="salesStats"></canvas>
            </div>*@
            <div>
                <div class="data display">
                    <p>$@ViewBag.CurrentMonthSales<sup>.00</sup></p>
                    <p>Trailing 30 Sales</p>
                </div>
                <div class="data display">
                    <p>@ViewBag.CloseRate<sup>%</sup></p>
                    <p>Close Rate</p>
                </div>
                <div class="data display">
                    <p>@ViewBag.OpenOpportunities</p>
                    <p>Open Opportunities</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="page-section opportunities" >
    <div onclick="Toggle(this)" class="heading-container">
        <h2 id="current-opportunities">Current Opportunities</h2>
        <ul>
            <li><a asp-action="SalespersonCreate" asp-controller="Project" asp-route-id="@Model.id">Create Project</a></li>
        </ul>
    </div>
    <div>
        <div class="row data-header">
            <p class="col-4">Opportunity Name</p>
            <p class="col-2">Estimate</p>
            <p class="col-2">Close Probability</p>
            <p class="col-2"></p>
            <p class="col-2"></p>
        </div>
        @foreach (Project project in Model.Projects.Where(p => p.IsSold == false).ToList())
        {
            <div class="row data-row">
                <p class="col-4">@project.Name</p>
                <p class="col-2">$@Math.Round(@project.Cost).00</p>
                <p class="col-2">@project.CloseNext()%</p>
                <p class="col-2"><a asp-controller="Project" asp-route-id="@project.id" asp-action="Details">Details</a></p>
                <p class="col-2"><a asp-controller="Project" asp-route-id="@project.id" asp-action="ConvertToSale">Convert To Sale</a></p>
            </div>
        }
    </div>
</div>
<script>

    var weeks =
        [
            "This Week",
            "First Previous",
            "Second Previous",
            "Third Previous"
        ];
    var salesPerMonth =
        [
            @ViewBag.ThirdPreviousWeekSales,
            @ViewBag.SecondPreviousWeekSales,
            @ViewBag.FirstPreviousWeekSales,
            @ViewBag.CurrentWeekSales
        ];

var data = {
    labels: weeks,
    datasets: [{
        label: 'Weekly Sales',
        backgroundColor: 'green',
        color: '#555',
        borderColor: 'rgb(255,99,132)',
        data: salesPerMonth
    }]
};
var config = {
    type: 'bar',
    data,
    options: {}
};

    var myChart = new Chart(
        document.getElementById('salesStats'),
        config
    );
</script>